<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDG45UHS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDG45UHS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDG45UHS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDG45UHS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDG45UHS\App_KernelDevDebugContainer([
    'container.build_hash' => 'DG45UHS',
    'container.build_id' => '9fddd3fb',
    'container.build_time' => 1744897196,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDG45UHS');
