<?php

namespace ContainerVEpWrGU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AgentController' shared autowired service.
     *
     * @return \App\Controller\AgentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AgentController.php';

        $container->services['App\\Controller\\AgentController'] = $instance = new \App\Controller\AgentController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\AgentRepository'] ?? $container->load('getAgentRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AgentController', $container));

        return $instance;
    }
}
