<?php

namespace ContainerDG45UHS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ScheduleController' shared autowired service.
     *
     * @return \App\Controller\ScheduleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ScheduleController.php';

        $container->services['App\\Controller\\ScheduleController'] = $instance = new \App\Controller\ScheduleController(($container->privates['App\\Repository\\AgentRepository'] ?? $container->load('getAgentRepositoryService')), ($container->privates['App\\Repository\\DemandRepository'] ?? $container->load('getDemandRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ScheduleController', $container));

        return $instance;
    }
}
